# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "LAKAYRAP"

# Avatar image path
avatar: "./images/logo.jpg"

# Name section text
name: "@lakayrap"

# Tagline section text
tagline: >-
    Du hip-hop, pour la culture.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-youtube"
      text: "CYPHER #1"
      url: "https://youtu.be/O5jxh5OAfIw"
      alt: "CYPHER #1"
      title: "CYPHER #1"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "Le Chilling S'Pod - jaS"
      url: "https://www.youtube.com/watch?v=GlpaBKCkScw"
      alt: "Le Chilling S'Pod - jaS"
      title: "Le Chilling S'Pod - jaS"
      target: "_blank"
 - link:
      icon: "fa-brands fa-youtube"
      text: "PELLICULE ARGENTIQUE FREESTYLE"
      url: "https://www.youtube.com/watch?v=Dcb5SiMD-gM"
      alt: "PELLICULE ARGENTIQUE FREESTYLE"
      title: "PELLICULE ARGENTIQUE FREESTYLE"
      target: "_blank"
#  - link:
#      icon: "fa-brands fa-swift"
 #     text: "ZMarkupParser <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMarkupParser']}} Stars)</span>"
  #    url: "https://github.com/ZhgChgLi/ZMarkupParser"
   #   alt: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
    #  title: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
     # target: "_blank"
#  - link:
 #     icon: "fa-brands fa-app-store-ios"
  #    text: "ZReviewTender <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZReviewTender']}} Stars)</span>"
   #   url: "https://github.com/ZhgChgLi/ZReviewTender"
    #  alt: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
     # title: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
     # target: "_blank"
#  - link:
 #     icon: "fa-brands fa-markdown"
  #    text: "ZMediumToMarkdown <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMediumToMarkdown']}} Stars)</span>"
   #   url: "https://github.com/ZhgChgLi/ZMediumToMarkdown"
    #  alt: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
   #   title: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
    #  target: "_blank"
 # - link:
  #    icon: "fa-brands fa-github"
   #   text: "linkyee <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/linkyee']}} Stars)</span>"
    #  url: "https://github.com/ZhgChgLi/linkyee"
     # alt: "linkyee is a fully customized, open-source LinkTree alternative deployed directly on GitHub Pages."
     # title: "linkyee is a fully customized, open-source LinkTree alternative deployed directly on GitHub Pages."
     # target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@LaKayRapOfficiel"
      title: "LaKayRap sur YouTube"
      alt: "LaKayRap sur YouTube"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/lakayrap"
      title: "LaKayRap sur Instagram"
      alt: "LaKayRap sur Instagram"
      target: "_blank"


# Footer text
footer: >
    Pull up au Coup d'État 2 frl

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://www.instagram.com/leossomething2" target="_blank">el batman</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
